apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: sample-app-stage
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  generators:
    - list:
        elements:
          - env: stage
            namespace: sample-app-stage
            valuesFile: values-stage.yaml
  template:
    metadata:
      name: 'sample-app-{{ .env }}'
      annotations:
        argocd.argoproj.io/sync-wave: "10"
    spec:
      project: default
      source:
        repoURL: https://github.com/ioaneN/gitops-platform-argocd.git
        targetRevision: master
        path: apps/sample-app
        helm:
          valueFiles:
            - '{{ .valuesFile }}'
      destination:
        name: in-cluster
        namespace: '{{ .namespace }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
